packages <- c("tidyverse"
              , "xlsx"
              , "data.table"
              , "lattice"
              , "vcd"
              , "vcdExtra"
              , "knitr"
              , "factoextra"
              , "FactoMineR"
              , "car"
              , "extracat"
              , "directlabels"
              , "devtools"
              , "repr"
              , "IRdisplay"
              , "digest"
              , "pbdZMQ"
              , "coda"
              , "pbapply"
              , "caret"
              , "parallel"
              , "doParallel"
              , "gam"
              , "ISLR"
              , "leaps"
              , "effects"
              , "tree"
              , "rpart"
              , "randomForest"
              , "glmnet"
              , "ElemStatLearn"
              , "gbm"
              , "class"
              , "pls"
              , "plotly"
              , "htmlwidgets"
              , "sqldf"
              , "pROC"
              , "corrgram"
              , "gpairs"
              , "binom"
              , "corrplot"
              , "gplots"
              , "coefplot"
              , "MCMCpack"
              , "nFactors"
              , "GPArotation"
              , "semPlot"
              , "semTools"
              , "cluster"
              , "forecast"
              , "lavaan"
              , "semPLS"
              , "mclust"
              , "poLCA"
              , "e1071"
              , "copula"
              , "arules"
              , "survminer"
              , "survival"
              , "Biograph"
              , "eha"
              , "faraway"
              , "QSARdata"
              , "HistData"
              , "pryr"
              , "neuralnet"
              , "NeuralNetTools"
              , "clusterGeneration"
              , "RMySQL"
              , "ape"
              , "sparcl"
              , "ggdendro"
              , "gramEvol"
              , "Hmisc"
              , "FSelector"
              , "mlbench"
              , "party"
              , "ROCR"
              , "ROSE"
              , "popbio"
              , "pastecs"
              , "modeest"
              , "fpc"
              , "arules"
              , "arulesViz"
              , "pspearman"
              , "ppcor"
              , "lsr"
              , "xgboost"
              , "scales"
              , "webshot"
              , "pwr"
              , "jmotif"
              , "tclust"
              , "seewave"
              , "psy"
              , "fmsb"
              , "irr"
              , "ada"
              , "tikzDevice"
              , "mcsm"
              , "rgp"
              , "arm"
              , "nlmeU"
              , "reshape"
              , "lme4"
              , "nlme"
              , "RLRsim"
              , "WWGbook"
              , "ellipse"
              , "LearnBayes"
              , "TeachingDemos"
              , "hexbin"
              , "geomnet"
              , "ggalt"
              , "Rttf2pt1"
              , "ggthemes"
              , "ggforce"
              , "ggtern"
              , "ordPens"
              , "bookdown"
              , "roxygen2"
              , "testthat"
              , "installr"
              , "moments"
              , "corrr"
              , "Matrix"
              , "SASmixed"
              , "mgcv"
              , "mlmRev"
              , "Zelig"
              , "VIM"
              , "mice"
              , "missForest"
              , "mi"
              , "mitools"
              , "cocor"
              , "LaplacesDemon"
              , "doRNG"
              , "arulesCBA"
              , "pander"
              , "Factoshiny"
              , "ECoL")

install.packages("countreg", repos="http://R-Forge.R-project.org")

# while (length(packages) > 0) {
#     tryCatch(install.packages(packages[1], dep=TRUE)
#              , finally = print(length(packages)))
#     packages <- packages[-1]
# }

for (p in tail(packages)) {
  if (!(require(p, character.only = TRUE))) {
    install.packages(p, dep=TRUE)
    require(p, character.only = TRUE)
  }
}

github.packages <- c("ndphillips/yarrr"
#                   , "IRkernel/IRkernel"
                    , 	"ramnathv/slidify"
                    , "ramnathv/slidifyLibraries"
                    , "JrEduardo/CountReg"
                    , "DougLuke/UserNetR"
                    , "Ather-Energy/ggTimeSeries"
                    , "rstudio/tensorflow"
                    , "hadley/colformat"
                    , "ropenscilabs/skimr"
                    , "rasmusab/bayesian_first_aid")

for (gp in tail(github.packages)) {
  if (!(require(gp, character.only = TRUE))) {
    devtools::install_github(gp)
    require(gp, character.only = TRUE)
  }
}

IRkernel::installspec()
